appComponent: product-catalog
environment: development
replicaCount: 1
image:
  repositoryName: product-catalog
  tag: v1
containerPort: 80
resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
mongoUsername: mongo
mongoPassword: mongo