appComponent: ui
environment: development
replicaCount: 1
image:
  repositoryName: 500731508494.dkr.ecr.us-east-1.amazonaws.com/eks-workshop-lbabay
  tag: ui
containerPort: 80
resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 64M1