apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.appComponent }}-{{ .Values.environment }}-svc"
  labels:
    {{- include "default-selector-labels" . | indent 2 }}
spec:
  selector:
    {{- include "default-selector-labels" . | indent 2 }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.containerPort }}